# -*- coding: utf-8 -*-

import names


def main():
    startApplication("FlowelementChart")
    clickButton(waitForObject(names.mainWidget_rect4_button_QPushButton))
    test.vp("VP1")
    clickButton(waitForObject(names.mainWidget_rhombus_button_QPushButton))
    test.vp("VP2")
    mouseClick(waitForObject(names.rect4_button_QGraphicsPathItem), 91, 45, Qt.NoModifier, Qt.LeftButton)
    dragItemBy(waitForObject(names.rect4_button_QGraphicsPathItem), 94, 44, 50, 220, 1, Qt.LeftButton)
    mouseClick(waitForObject(names.mainWidget_rect4_button_Canvas), 709, 270, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP3")
    clickButton(waitForObject(names.mainWidget_arrow_button_QPushButton))
    mouseClick(waitForObject(names.rect4_button_QGraphicsPathItem_2), 132, 101, Qt.NoModifier, Qt.LeftButton)
    mouseClick(waitForObject(names.mainWidget_rect4_button_Canvas), 300, 321, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP4")
    mouseClick(waitForObject(names.rect4_button_QGraphicsPathItem_2), 166, 44, Qt.NoModifier, Qt.LeftButton)
    mouseClick(waitForObject(names.rect4_button_QGraphicsPathItem_2), 193, 52, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP5")
    clickButton(waitForObject(names.mainWidget_arrow_button_QPushButton))
    mouseClick(waitForObject(names.rect4_button_QGraphicsPathItem), 111, 50, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.mainWidget_color_button_QPushButton))
    mouseClick(waitForObject(names.basic_colors_QtPrivate_QWellArray), 149, 60, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.select_Color_OK_QPushButton))
    mouseClick(waitForObject(names.mainWidget_rect4_button_Canvas), 690, 336, Qt.NoModifier, Qt.LeftButton)
    test.vp("VP6")
    
    # 撤销
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 138, 20, Qt.LeftButton, 0, 0)
    test.vp("VP5")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 135, 12, Qt.LeftButton, 0, 0)
    test.vp("VP4")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 135, 12, Qt.LeftButton, 0, 0)
    test.vp("VP3")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 135, 12, Qt.LeftButton, 0, 0)
    test.vp("VP2")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 135, 12, Qt.LeftButton, 0, 0)
    test.vp("VP1")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 135, 12, Qt.LeftButton, 0, 0)
    test.vp("VP0")
    
    # 重做
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 9, Qt.LeftButton, 0, 0)
    test.vp("VP1")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 9, Qt.LeftButton, 0, 0)
    test.vp("VP2")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 9, Qt.LeftButton, 0, 0)
    test.vp("VP3")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 9, Qt.LeftButton, 0, 0)
    test.vp("VP4")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 9, Qt.LeftButton, 0, 0)
    test.vp("VP5")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 9, Qt.LeftButton, 0, 0)
    test.vp("VP6")
