# encoding: UTF-8

from objectmaphelper import *

mainWidget_MainWidget = {"name": "MainWidget", "type": "MainWidget", "visible": 1}
mainWidget_rect4_button_QPushButton = {"name": "rect4_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_rhombus_button_QPushButton = {"name": "rhombus_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_QMenuBar = {"type": "QMenuBar", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
mainWidget_rect3_button_QPushButton = {"name": "rect3_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_menuWidget_QWidget = {"name": "menuWidget", "type": "QWidget", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_rect4_button_Canvas = {"aboveWidget": mainWidget_menuWidget_QWidget, "leftWidget": mainWidget_rect4_button_QPushButton, "type": "Canvas", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
rect4_button_QGraphicsPathItem = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ffffff", "focusable": "no", "lineColor": "#000000", "lineWidth": 2, "movable": "no", "occurrence": 2, "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
rect4_button_QGraphicsPathItem_2 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ffffff", "focusable": "no", "lineColor": "#000000", "lineWidth": 2, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
mainWidget_rect2_button_QPushButton = {"name": "rect2_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_parallelogram_button_QPushButton = {"name": "parallelogram_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_rect_button_QPushButton = {"name": "rect_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_circle_button_QPushButton = {"name": "circle_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_roundrect_button_QPushButton = {"name": "roundrect_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_arrow_button_QPushButton = {"name": "arrow_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
rect4_button_QGraphicsPathItem_3 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "focusable": "no", "lineColor": "#000000", "lineWidth": 3, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
mainWidget_arrow_button_QPushButton_2 = {"aboveWidget": mainWidget_arrow_button_QPushButton, "type": "QPushButton", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
rect4_button_QGraphicsRectItem = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff0000", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 1, "movable": "no", "occurrence": 2, "selectable": "no", "type": "QGraphicsRectItem", "visible": "no"}
rect4_button_QGraphicsRectItem_2 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff0000", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 1, "movable": "no", "selectable": "no", "type": "QGraphicsRectItem", "visible": "no"}
rect4_button_Text_here_GraphicsTextItem = {"acceptDrops": "yes", "container": mainWidget_rect4_button_Canvas, "editable": "no", "enabled": "yes", "focusable": "no", "movable": "no", "selectable": "yes", "text": "Text here.", "type": "GraphicsTextItem", "visible": "yes"}
rect4_button_Text_here_GraphicsTextItem_2 = {"acceptDrops": "yes", "container": mainWidget_rect4_button_Canvas, "editable": "no", "enabled": "yes", "focusable": "no", "movable": "no", "occurrence": 2, "selectable": "yes", "text": "Text here.", "type": "GraphicsTextItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_9 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#000000", "focusable": "no", "lineColor": "#000000", "lineWidth": 1, "movable": "no", "occurrence": 3, "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_8 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#000000", "focusable": "no", "lineColor": "#000000", "lineWidth": 1, "movable": "no", "occurrence": 2, "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_7 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#000000", "focusable": "no", "lineColor": "#000000", "lineWidth": 1, "movable": "no", "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_6 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff0000", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 1, "movable": "no", "occurrence": 4, "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_5 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff0000", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 1, "movable": "no", "occurrence": 3, "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_4 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff0000", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 1, "movable": "no", "occurrence": 2, "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_3 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff0000", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 1, "movable": "no", "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
rect4_button_QGraphicsRectItem_10 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#000000", "focusable": "no", "lineColor": "#000000", "lineWidth": 1, "movable": "no", "occurrence": 4, "selectable": "no", "type": "QGraphicsRectItem", "visible": "yes"}
mainWidget_searchBox_QLineEdit = {"name": "searchBox", "type": "QLineEdit", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_searchButton_QPushButton = {"name": "searchButton", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
mainWidget_color_button_QPushButton = {"name": "color_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
select_Color_QColorDialog = {"type": "QColorDialog", "unnamed": 1, "visible": 1, "windowTitle": "Select Color"}
select_Color_Basic_colors_QLabel = {"text": "Basic colors", "type": "QLabel", "unnamed": 1, "visible": 1, "window": select_Color_QColorDialog}
basic_colors_QtPrivate_QWellArray = {"buddy": select_Color_Basic_colors_QLabel, "type": "QtPrivate::QWellArray", "unnamed": 1, "visible": 1}
select_Color_OK_QPushButton = {"text": "OK", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": select_Color_QColorDialog}
mainWidget_border_color_button_QPushButton = {"name": "border_color_button", "type": "QPushButton", "visible": 1, "window": mainWidget_MainWidget}
select_Border_Color_QColorDialog = {"type": "QColorDialog", "unnamed": 1, "visible": 1, "windowTitle": "Select Border Color"}
select_Border_Color_Basic_colors_QLabel = {"text": "Basic colors", "type": "QLabel", "unnamed": 1, "visible": 1, "window": select_Border_Color_QColorDialog}
basic_colors_QtPrivate_QWellArray_2 = {"buddy": select_Border_Color_Basic_colors_QLabel, "type": "QtPrivate::QWellArray", "unnamed": 1, "visible": 1}
select_Border_Color_OK_QPushButton = {"text": "OK", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": select_Border_Color_QColorDialog}
rect4_button_QGraphicsPathItem_4 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#00ff7f", "focusable": "no", "lineColor": "#aa0000", "lineWidth": 2, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
rect4_button_GraphicsTextItem = {"acceptDrops": "yes", "container": mainWidget_rect4_button_Canvas, "editable": "yes", "enabled": "yes", "focusable": "yes", "movable": "no", "selectable": "yes", "type": "GraphicsTextItem", "visible": "yes"}
rect4_button_QGraphicsPathItem_5 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#00ff7f", "focusable": "no", "lineColor": "#000000", "lineWidth": 2, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
select_Border_Color_HTML_QLabel = {"text": "HTML:", "type": "QLabel", "unnamed": 1, "visible": 1, "window": select_Border_Color_QColorDialog}
qt_colorname_lineedit_QLineEdit = {"buddy": select_Border_Color_HTML_QLabel, "name": "qt_colorname_lineedit", "type": "QLineEdit", "visible": 1}
rect4_button_QGraphicsPathItem_6 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "focusable": "no", "lineColor": "#ff0000", "lineWidth": 3, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
select_Color_HTML_QLabel = {"text": "HTML:", "type": "QLabel", "unnamed": 1, "visible": 1, "window": select_Color_QColorDialog}
qt_colorname_lineedit_QLineEdit_2 = {"buddy": select_Color_HTML_QLabel, "name": "qt_colorname_lineedit", "type": "QLineEdit", "visible": 1}
rect4_button_QGraphicsPathItem_7 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff5500", "focusable": "no", "lineColor": "#000000", "lineWidth": 2, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
rect4_button_QGraphicsPathItem_8 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ff5500", "focusable": "no", "lineColor": "#00ff00", "lineWidth": 2, "movable": "no", "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
rect4_button_QGraphicsPathItem_9 = {"acceptDrops": "no", "container": mainWidget_rect4_button_Canvas, "enabled": "yes", "fillColor": "#ffffff", "focusable": "no", "lineColor": "#000000", "lineWidth": 2, "movable": "no", "occurrence": 3, "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
mainWidget_QWidget = {"occurrence": 2, "type": "QWidget", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
mainWidget_File_QMenu = {"title": "File", "type": "QMenu", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
qFileDialog_QFileDialog = {"name": "QFileDialog", "type": "QFileDialog", "visible": 1}
qFileDialog_fileNameLabel_QLabel = {"name": "fileNameLabel", "type": "QLabel", "visible": 1, "window": qFileDialog_QFileDialog}
fileNameEdit_QLineEdit = {"buddy": qFileDialog_fileNameLabel_QLabel, "name": "fileNameEdit", "type": "QLineEdit", "visible": 1}
qFileDialog_Save_QPushButton = {"text": "Save", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": qFileDialog_QFileDialog}
qFileDialog_splitter_QSplitter = {"name": "splitter", "type": "QSplitter", "visible": 1, "window": qFileDialog_QFileDialog}
splitter_frame_QFrame = {"container": qFileDialog_splitter_QSplitter, "name": "frame", "type": "QFrame", "visible": 1}
frame_stackedWidget_QStackedWidget = {"container": splitter_frame_QFrame, "name": "stackedWidget", "type": "QStackedWidget", "visible": 1}
stackedWidget_treeView_QTreeView = {"container": frame_stackedWidget_QStackedWidget, "name": "treeView", "type": "QTreeView", "visible": 1}
treeView_1221svgtest_svg_QModelIndex = {"column": 0, "container": stackedWidget_treeView_QTreeView, "text": "1221svgtest.svg", "type": "QModelIndex"}
o_QListView = {"text": "Save", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": qFileDialog_QFileDialog}
o_QInputDialog = {"aboveWidget": mainWidget_menuWidget_QWidget, "leftWidget": mainWidget_rect4_button_QPushButton, "type": "Canvas", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
o_QLabel = {"text": "请输入要替换成的字符串", "type": "QLabel", "unnamed": 1, "visible": 1, "window": o_QInputDialog}
o_QLineEdit = {"buddy": o_QLabel, "type": "QLineEdit", "unnamed": 1, "visible": 1}
o_OK_QPushButton = {"text": "OK", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_QInputDialog}
rect4_button_Textchange_here_GraphicsTextItem = {"acceptDrops": "yes", "container": mainWidget_rect4_button_Canvas, "editable": "no", "enabled": "yes", "focusable": "no", "movable": "no", "selectable": "yes", "text": "Textchange here.", "type": "GraphicsTextItem", "visible": "yes"}
mainWidget_Edit_QMenu = {"title": "Edit", "type": "QMenu", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
splitter_sidebar_QSidebar = {"container": qFileDialog_splitter_QSplitter, "name": "sidebar", "type": "QSidebar", "visible": 1}
qFileDialog_Open_QPushButton = {"text": "Open", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": qFileDialog_QFileDialog}
mainWidget_QScrollBar = {"type": "QScrollBar", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
mainWidget_QScrollBar_2 = {"occurrence": 2, "type": "QScrollBar", "unnamed": 1, "visible": 1, "window": mainWidget_MainWidget}
rect4_button_QGraphicsPathItem_10 = {"acceptDrops": "no", "container": o_QInputDialog, "enabled": "yes", "fillColor": "#ffffff", "focusable": "no", "lineColor": "#000000", "lineWidth": 2, "movable": "no", "occurrence": 6, "selectable": "yes", "type": "QGraphicsPathItem", "visible": "yes"}
o_QInputDialog_2 = {"type": "QInputDialog", "unnamed": 1, "visible": 1, "windowTitle": "查找和替换"}
o_QLabel_2 = {"text": "请输入要替换成的字符串", "type": "QLabel", "unnamed": 1, "visible": 1, "window": o_QInputDialog_2}
o_QLineEdit_2 = {"buddy": o_QLabel_2, "type": "QLineEdit", "unnamed": 1, "visible": 1}
o_OK_QPushButton_2 = {"text": "OK", "type": "QPushButton", "unnamed": 1, "visible": 1, "window": o_QInputDialog_2}
