# -*- coding: utf-8 -*-

import names


def main():
    startApplication("FlowelementChart")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Edit"))
    activateItem(waitForObjectItem(names.mainWidget_Edit_QMenu, "Background"))
    mouseClick(waitForObjectItem(names.splitter_sidebar_QSidebar, "My Computer"), 93, 18, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObjectItem(names.stackedWidget_treeView_QTreeView, "Windows-SSD (C:)"), 81, 11, Qt.NoModifier, Qt.LeftButton)
    mouseClick(waitForObjectItem(names.splitter_sidebar_QSidebar, "My Computer"), 100, 14, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObjectItem(names.stackedWidget_treeView_QTreeView, "新加卷 (E:)"), 89, 8, Qt.NoModifier, Qt.LeftButton)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 135, 247, 120, 0, 2)
    doubleClick(waitForObjectItem(names.stackedWidget_treeView_QTreeView, "Desktop"), 116, 18, Qt.NoModifier, Qt.LeftButton)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 137, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 141, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.stackedWidget_treeView_QTreeView), 115, 143, -120, 0, 2)
    mouseClick(waitForObjectItem(names.stackedWidget_treeView_QTreeView, "pic\\.jpg"), 121, 17, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.qFileDialog_Open_QPushButton))
    test.vp("VP1_pic_back")
    
    # 滚动 不自适应
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 624, 334, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 624, 334, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 624, 334, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 624, 334, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 624, 334, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 331, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 622, 330, -120, 0, 2)
    test.vp("VP1_pic_back")
    
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 635, 54, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 635, 54, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 635, 54, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 57, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 57, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    sendEvent("QWheelEvent", waitForObject(names.mainWidget_rect4_button_Canvas), 636, 59, 120, 0, 2)
    test.vp("VP1_pic_back")
    
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Edit"))
    activateItem(waitForObjectItem(names.mainWidget_Edit_QMenu, "Grid Background"))
    test.vp("VP1_grid_back")
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 139, 25, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 139, 25, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 139, 25, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 139, 25, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 129, 13, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 129, 13, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 129, 13, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 129, 13, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 129, 13, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 129, 13, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 129, 13, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 129, 13, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 129, 13, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 12, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 193, 12, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 12, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo_2"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 12, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 193, 12, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 193, 12, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 145, 9, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonDblClick, 145, 9, Qt.LeftButton, 1, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 145, 9, Qt.LeftButton, 0, 0)
    activateItem(waitForObjectItem(names.mainWidget_QMenuBar, "Redo"))
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 145, 9, Qt.LeftButton, 0, 0)
    sendEvent("QMouseEvent", waitForObject(names.mainWidget_QMenuBar), QEvent.MouseButtonRelease, 680, 4, Qt.LeftButton, 0, 0)
    sendEvent("QCloseEvent", waitForObject(names.mainWidget_MainWidget))
    
